### ISSUE TITLE
re: angular version

### ISSUE THREAD

**Issue by jamesvanleuven** [DHTMLX/angular-scheduler-demo#4]
Hiya,

I'm taking a look at your repo (and have forked it) and was wondering if you've done anything which you've not uploaded to this repo using a different version of angular. I'm using v1.3.15. I noticed your version is dramatically older.

If you don't mind, I'd like to bang away at this with some changes to update it for the version I'm using?

**Comment by AlexKlimenkov** [comment]
Hi,
I've updated angularjs in this demo https://github.com/DHTMLX/angular-scheduler-demo/commit/983d6d99cd4e35f40d07af91bfd39bbd91980f71 , although all seemed to be backward compatible.
