### ISSUE TITLE
Angular 11 | 12 support

### ISSUE THREAD

**Issue by bitkorn** [DHTMLX/angular-scheduler-demo#4]
`npm install` produce plenty deprecations and errors.

The tutorial at [dhtmlx.com](https://dhtmlx.com/blog/angular-dhtmlxscheduler-tutorial/) is very simple, but does not work.

Since there was already no response to the issue with Angular 7, I suspect that the project is dead ... too bad, DHTMLX seemed to be a good thing :(

Is there anyone else working on the project?

**Comment by SergMitMin** [comment]
Hello,

The following tutorial is a little bit outdated and we working on the new one, unfortunately, there is no ETA.

Here is an example of using the `scheduler/gantt` in the `Angular 11`:
https://files.dhtmlx.com/30d/2ce72c35d2b5d86b149e8bd361ebe70b/angular11+gantt__GPL+scheduler_GPL.zip


Run `yarn install` command
Run `yarn start` command
